# Generated by Django 4.2.5 on 2023-10-07 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffeename',
            options={},
        ),
        migrations.RemoveField(
            model_name='coffeename',
            name='user',
        ),
    ]
