# Generated by Django 4.2.5 on 2023-10-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_coffeename_options_remove_coffeename_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeename',
            name='complete',
        ),
    ]
