# Generated by Django 4.2.5 on 2023-10-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_coffeename_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeename',
            old_name='title',
            new_name='Coffee_Name',
        ),
    ]
