# Generated by Django 4.2.5 on 2023-10-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_title_coffeename_coffee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeename',
            old_name='Coffee_Name',
            new_name='title',
        ),
    ]
