# Generated by Django 4.2.5 on 2023-10-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_coffee_name_coffeename_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeename',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
