# Generated by Django 4.2.5 on 2023-10-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_coffeename_price'),
        ('shop', '0002_remove_products_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
